version: '3'

services:
  server_core:
    image: nats:2.8.4-alpine
    command: -c /etc/server.conf --name nats_core
    volumes:
      - ../../../nats-core/nats.conf:/etc/server.conf
    networks:
      - default
  core_req:
    image: ec2ainun/core-req
    command: "profit.get"
    depends_on:
      - "server_core"
      - "core_rep"
    networks:
      - default
  core_rep:
    image: ec2ainun/core-rep
    command: -q poc "profit.get"
    depends_on:
      - "server_core"
    networks:
      - default

networks:
  default: {}