version: '3'

services:
  publish:
    image: ec2ainun/producer-sync
    command: -msgs 10000 "profit.id"
    networks:
      - data-stream
  subscribe:
    image: ec2ainun/consumer-push
    command: -sn profit -cn one-push-cprofit_id -s "profit.id"
    networks:
      - data-stream

networks:
  data-stream:
    external: true